# Generated by Django 5.0.1 on 2024-02-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ID", models.CharField(max_length=10)),
                ("photo", models.ImageField(blank=True, upload_to="photos/")),
                ("grade", models.CharField(max_length=2)),
                ("certificate", models.BooleanField(default=False)),
            ],
        ),
    ]
